### PR TITLE
Switch to github action

### PR DESCRIPTION
**Pull request by roidelapluie**
Signed-off-by: Julien Pivotto <roidelapluie@o11y.eu>

### CODE REVIEW

**Comment by roidelapluie** [comment]
@matthiasr this would require you to rename the default branch to main

**Comment by matthiasr** [comment]
Unless you are ready to switch over all projects at the drop of a hat, let's hold off on this – it seems like this would affect all Prometheus Go builds as soon as they enter the CircleCI rollout. I got information from support on how to fix it, will make a PR against the Orb shortly!

**Comment by matthiasr** [comment]
That is, I'm happy to switch over the exporter, but right now it's our canary in the coal mine for this rollout. I would like to see that what they propose fixes the issue before we lose this opportunity.

**Comment by matthiasr** [comment]
Oh, it seems that @simonpasquier already came to the same conclusion:

https://github.com/prometheus/circleci/pull/28

**Comment by roidelapluie** [comment]
> Unless you are ready to switch over all projects at the drop of a hat, let's hold off on this – it seems like this would affect all Prometheus Go builds as soon as they enter the CircleCI rollout. I got information from support on how to fix it, will make a PR against the Orb shortly!

The change is ongoing for multiple repositories. Prometheus, haproxy_exporter, and promlens are on GitHub action. There is a PR for consul exporter. More repos will switch later this year.

**Review by jan--f — APPROVED** [review]
This looks good to me.
I see two optional improvements:

1. The publish job names use `artefacts` and `artifacts`. Using one them consistently might be an improvement.
2. The `ci` workflow could be split up into `ci` and `release` workflows, where `release` reuses the CI workflow. I think that would improve clarity when a workflow is triggered (no need for `if:` filters) and PRs wouldn't have the skipped release jobs in the checks list.

I'd be happy to do the leg work but wanted to propose it first.

**Comment by matthiasr** [comment]
Great, I've seen what I wanted to see – the CircleCI orb 0.17.1 fixes the issues, so it can tide the remaining repositories over if needed.

**Review by matthiasr — APPROVED** [review]

**Pull request merged**
